### ISSUE TITLE
Regarding `tr.appmia.com`

### ISSUE THREAD

**Issue by spirillen** [AssoEchap/stalkerware-indicators#121]
We at My Privacy DNS have imported this domain from your source some time ago, and today I was walking through the lists unmanned #Spyware domains and this come up https://0xacab.org/my-privacy-dns/matrix/-/issues/89838 But when I'm visiting the domain it look like it is taken over by `parkingcrew.net`: https://0xacab.org/my-privacy-dns/matrix/-/issues/20936

The question is, why did out bot through it back at me, saying it not a Pirated domain?? do you happen to know something I don't?

**Comment by jvoisin** [comment]
I don't understand your question. `tr.appmia.com` was used by a stalkerware, but now the domain expired, and is now parked.

**Comment by spirillen** [comment]
Thanks
