### ISSUE TITLE
two quad9 blocklists

### ISSUE THREAD

**Issue by e075e** [AssoEchap/stalkerware-indicators#124]
This repo has two quad9 lists, the first is 3 weeks old while the last is 2 years old. Is it fine?

https://github.com/AssoEchap/stalkerware-indicators/blob/master/generated/quad9_blocklist.txt

https://github.com/AssoEchap/stalkerware-indicators/blob/master/quad9_blocklist.txt

Thanks

**Comment by Te-k** [comment]
Yes indeed, we kept both for the transition to the new file, but it turns out we forgot to remove the old one, I just removed it. Thanks!
