### ISSUE TITLE
1topspy.com

### ISSUE THREAD

**Issue by spirillen** [AssoEchap/stalkerware-indicators#128]
`1topspy.com` is a parked domain and should be considered as discontinued from spyware industry

## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

```css
data/assoEchap.csv:1topspy.com
data/assoEchap.csv:flushdata.1topspy.com
data/stalkerware-indicators.csv:1topspy.com
data/stalkerware-indicators.csv:flushdata.1topspy.com
```

#### Sorted result

```css
flushdata.1topspy.com
```

### Search result from easylist

```css
```

## Search in [Matrix](https://www.mypdns.org/)

Search results from [Matrix](https://www.mypdns.org) blacklist project

```css
```

Did not find any matching RPZ records

Any known matrix issues?

\+ We did not find any existing issues for the domain in Matrix

+++++++++++++++++++++++++++++++++++++++
\+ Thanks to [My Privacy DNS](https://www.mypdns.org/) for this knowledge +
+++++++++++++++++++++++++++++++++++++++

Drilling for 1topspy.com

```bash
1topspy.com.    172800  IN      NS      ns15.abovedomains.com.
1topspy.com.    172800  IN      NS      ns16.abovedomains.com.
1topspy.com.    3600    IN      A       103.224.212.212
```

**Comment by jvoisin** [comment]
The domain being parked doesn't prevent devices infected with topspy from trying to reach it, thus we're keeping outdated/expired/parked domains in the list of IoC.
