### ISSUE TITLE
Investigate Spyrix Software

### ISSUE THREAD

**Issue by Epicurean7734** [AssoEchap/stalkerware-indicators#131]
Hello. I did not see this one mentioned in your list, so I thought I'd bring it to your attention to investigate if you haven't yet.

This software can monitor someone's Windows, macOS or Android device. They mention a keylogger, being able to take screenshots, using the camera, apparently having facial recognition and more. I had a quick look through their blog and they have at least one about installing their Android app on a husband's phone to track them, a couple for parents using it on children's devices to "keep them safe", a lot are for employers and at least one about how an employee could tell if their boss had similar software on a work device.

Website: https://www.spyrix.com

Tacking husband's phone blog post: https://www.spyrix.com/how-to-put-a-tracker-on-my-husband-phone.php

They specifically mention in that blog post: "The phone tracker is working in a hidden mode. Nobody will know you track your husband’s/kid’s phone"

**Comment by jvoisin** [comment]
Done in 76d660d93715c39c7588a6c9b7ed122f37fd2e9b, thanks

**Comment by kpcyrd** [comment]
fwiw it looks like `www.spyrix.com` and `spyrix.com` were already present in the `website:` dictionary. :)
