### ISSUE TITLE
Generic and publicly accessible APK certificate added as indicator for KidsShield

### ISSUE THREAD

**Issue by DonnchaC** [AssoEchap/stalkerware-indicators#132]
The APK certificate `61ED377E85D386A8DFEE6B864BD85B0BFAA5AF81` appears to be a debug certificate with a publicly accessible private key. This is widely available such as at https://github.com/mfonville/pa_gapps/blob/master/testkey.pk8. 

```
Owner: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
Issuer: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
Serial number: 936eacbe07f201df
Valid from: Fri Feb 29 02:33:46 CET 2008 until: Tue Jul 17 03:33:46 CEST 2035
Certificate fingerprints:
	 SHA1: 61:ED:37:7E:85:D3:86:A8:DF:EE:6B:86:4B:D8:5B:0B:FA:A5:AF:81
	 SHA256: A4:0D:A8:0A:59:D1:70:CA:A9:50:CF:15:C1:8C:45:4D:47:A3:9B:26:98:9D:8B:64:0E:CD:74:5B:A7:1B:F5:DC
Signature algorithm name: SHA1withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3
```

Clearly any app signed by such a key would be insecure and so should be flagged. That cert is currently associated with `KidsShield` which is confusing. Would it be possible to move this cert and any other known abused certs to a separate IOC category?

**Comment by Te-k** [comment]
Done, thanks!
