### ISSUE TITLE
Transfer repository

### ISSUE THREAD

**Issue by Te-k** [AssoEchap/stalkerware-indicators#80]
Actions : 
* [x] Update Quad9 URL
* [x] Update [TinyCheck URL](https://github.com/KasperskyLab/TinyCheck/pull/111/files)
* [x] Update NextDNS 
* [x] Update Adguard url
* [x] [firebog](https://github.com/WaLLy3K/wally3k.github.io/pull/162)

**Comment by Te-k** [comment]
@jvoisin Could you update https://github.com/AdguardTeam/HostlistsRegistry/pull/35 with the new urls?

**Comment by jvoisin** [comment]
Done.

**Comment by Te-k** [comment]
You're fast
