### ISSUE TITLE
Improve management of generated files

### ISSUE THREAD

**Issue by Te-k** [AssoEchap/stalkerware-indicators#88]
Having an action pushing updated generated files creates problems with forks and PR, how can we improve that?

Maybe a git pre-commit hook + a daily option?

**Comment by kpcyrd** [comment]
You could use something like `if: github.repository == 'AssoEchap/stalkerware-indicators'` to prevent the workflow from running in forks. :)

**Comment by Te-k** [comment]
Thanks @U039b
