### ISSUE TITLE
Change the license

### ISSUE THREAD

**Issue by jvoisin** [AssoEchap/stalkerware-indicators#91]
Switch to CC-BY-SA, and add some text explaining that if the license is problematic, please do reach out, we're happy to figure something out.

**Comment by Te-k** [comment]
Done with 5672b828df80d903f89b287320f9be8bf55da148

**Comment by jvoisin** [comment]
I thought a bit about it, and asked around. I don't think the `SA` is useful nor desirable: we don't care what people do with our IoC, nor if they bundle it in their anti-virus/WAF/… under whatever license they want, as long as we're credited somewhere.

**Comment by Te-k** [comment]
It works for me
