### ISSUE TITLE
Add a tag "watchware"/"surveillanceware"

### ISSUE THREAD

**Issue by jvoisin** [AssoEchap/stalkerware-indicators#96]
For shady-but-not-stalkerware things like https://play.google.com/store/apps/details?id=com.mspy.lite

- Create a `hosts_full.txt` and a `hosts.txt` file.
- Tags in suricata
- Document this in the readme

**Comment by jvoisin** [comment]
Tag added via 25fd089d47c92677c612f0bb070a20f1d937df04

**Comment by Te-k** [comment]
Done with a785832a730a45bf2b6f83154521e6864cace3d2
