### ISSUE TITLE
Add "trackingsmartphone" APK's

### ISSUE THREAD

**Issue by DrWhax** [AssoEchap/stalkerware-indicators#99]
https://trackingsmartphone.com/app-download/

- https://www.virustotal.com/gui/file/a7d65ad2e1a5afb761c226caf684cfd09e86451b75e849c3a5b32aefc53ee511/detection
- https://www.virustotal.com/gui/file/e17f6d7076f58b3ad5bf6eb286711cfbe171b0c2e2ae8d7dd519b386be421548

**Comment by jvoisin** [comment]
We've got the samples in our mwdb instance :P
